import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { ChromaClient } from 'chromadb';
import { OpenAI } from 'openai';

const openai = new OpenAI({
  apiKey: process.env.GITHUB_TOKEN,
  baseURL: 'https://models.github.ai/inference',
});

const chroma = new ChromaClient();
const DOCS_DIR = path.join(process.cwd(), 'docs');
const EMBEDDING_MODEL = 'openai/text-embedding-3-small';

// We always pass embeddings explicitly, so Chroma never needs to generate
// its own — this stub avoids it trying to load @chroma-core/default-embed.
const noopEmbeddingFunction = {
  generate: async () => {
    throw new Error('Embeddings should be provided manually and never generated by Chroma.');
  },
};

export function chunkText(text, size = 400) {
  // Split on paragraph boundaries first, then fall back to hard size limit.
  // Paragraph-aware chunks keep semantically related sentences together,
  // which produces tighter, more accurate embeddings than fixed-size slicing.
  const paragraphs = text.split(/\n{2,}/);
  const chunks = [];
  let current = '';

  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) continue;
    if (current.length + trimmed.length + 2 > size && current.length > 0) {
      chunks.push(current.trim());
      current = trimmed;
    } else {
      current = current ? `${current}\n\n${trimmed}` : trimmed;
    }
  }
  if (current.trim()) chunks.push(current.trim());

  // If any individual paragraph exceeds `size`, hard-split it
  return chunks.flatMap((c) =>
    c.length <= size ? [c] : c.match(new RegExp(`.{1,${size}}`, 'gs')) ?? []
  );
}

/**
 * Chunks a file's text, embeds each chunk, and upserts it into the `docs`
 * collection under that filename. Shared by ingestFile() below and by the
 * gap-detect draft-approval flow, which ingests an approved stub the moment
 * it's approved (see listeners/actions/draft_approval.js).
 */
export async function ingestText(fileName, text) {
  try {
    const chunks = chunkText(text);
    const collection = await chroma.getOrCreateCollection({
      name: 'docs',
      embeddingFunction: noopEmbeddingFunction,
    });

    // Clear any chunks already stored under this filename first. Without
    // this, re-ingesting an existing doc (e.g. an approved correction that
    // overwrites docs/handbook.md) either fails on duplicate ids or, if the
    // new content chunks to fewer pieces than before, leaves old trailing
    // chunks behind that still get retrieved alongside the corrected ones.
    try {
      await collection.delete({ where: { source: fileName } });
    } catch (error) {
      console.warn(`No existing chunks to clear for ${fileName} (or delete failed): ${error.message}`);
    }

    for (const [i, chunk] of chunks.entries()) {
      const embedding = await openai.embeddings.create({ model: EMBEDDING_MODEL, input: chunk });
      await collection.add({
        ids: [`${fileName}-${i}`],
        embeddings: [embedding.data[0].embedding],
        documents: [chunk],
        metadatas: [{ source: fileName }],
      });
    }
    return chunks.length;
  } catch (error) {
    console.error(`ChromaDB error during ingestion of ${fileName}:`, error.message);
    throw error;
  }
}

export async function ingestFile(filePath) {
  const text = fs.readFileSync(filePath, 'utf-8');
  const fileName = path.basename(filePath);
  const count = await ingestText(fileName, text);
  console.log(`Ingested ${count} chunks from ${fileName}`);
}

async function main() {
  if (!fs.existsSync(DOCS_DIR)) {
    console.warn(`No docs/ folder found at ${DOCS_DIR}. Create it and add Markdown files to ingest.`);
    return;
  }

  const files = fs.readdirSync(DOCS_DIR).filter((f) => f.toLowerCase().endsWith('.md'));

  if (files.length === 0) {
    console.warn(`No .md files found in ${DOCS_DIR}. Add at least one .md file and rerun.`);
    return;
  }

  console.log(`Attempting to ingest ${files.length} file(s)...`);
  let successCount = 0;
  for (const file of files) {
    try {
      await ingestFile(path.join(DOCS_DIR, file));
      successCount++;
    } catch (error) {
      console.error(`Failed to ingest ${file}: ${error.message}`);
    }
  }
  console.log(`Successfully ingested ${successCount}/${files.length} file(s)`);
}

// Only run main() when this file is executed directly (node ingest.js),
// not when imported as a module by app.js or tests.
const isMain = process.argv[1] && (
  process.argv[1].endsWith('/ingest.js') ||
  process.argv[1].endsWith('\\ingest.js')
);
if (isMain) main();