import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { ChromaClient } from 'chromadb';
import { OpenAI } from 'openai';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __filename = fileURLToPath(import.meta.url);
const require = createRequire(__filename);
const pdf = require('pdf-parse');

const openai = new OpenAI({
  apiKey: process.env.GITHUB_TOKEN,
  baseURL: 'https://models.github.ai/inference',
});
const chroma = new ChromaClient();
const DOCS_DIR = path.join(process.cwd(), 'docs');
const EMBEDDING_MODEL = 'openai/text-embedding-3-small';

// We always pass embeddings explicitly, so Chroma never needs to generate
// its own — this stub avoids it trying to load @chroma-core/default-embed.
const noopEmbeddingFunction = {
  generate: async () => {
    throw new Error('Embeddings should be provided manually and never generated by Chroma.');
  },
};

function chunkText(text, size = 1000) {
  return text.match(new RegExp(`.{1,${size}}`, 'gs')) || [];
}

async function ingestFile(filePath) {
  const buffer = fs.readFileSync(filePath);
  const data = await pdf(buffer);
  const text = data.text;
  const chunks = chunkText(text);

  const collection = await chroma.getOrCreateCollection({
    name: 'docs',
    embeddingFunction: noopEmbeddingFunction,
  });
  const fileName = path.basename(filePath);

  for (const [i, chunk] of chunks.entries()) {
    const embedding = await openai.embeddings.create({
      model: EMBEDDING_MODEL,
      input: chunk,
    });
    await collection.add({
      ids: [`${fileName}-${i}`],
      embeddings: [embedding.data[0].embedding],
      documents: [chunk],
      metadatas: [{ source: fileName }],
    });
  }
  console.log(`Ingested ${chunks.length} chunks from ${fileName}`);
}

async function main() {
  if (!fs.existsSync(DOCS_DIR)) {
    console.error(`No docs/ folder found at ${DOCS_DIR}. Create it and add PDFs to ingest.`);
    process.exit(1);
  }

  const files = fs.readdirSync(DOCS_DIR).filter((f) => f.toLowerCase().endsWith('.pdf'));

  if (files.length === 0) {
    console.error(`No PDFs found in ${DOCS_DIR}. Add at least one .pdf file and rerun.`);
    process.exit(1);
  }

  for (const file of files) {
    await ingestFile(path.join(DOCS_DIR, file));
  }
}

main();
