import { ChromaClient } from 'chromadb';

const chromaUrl = process.env.CHROMA_URL ?? 'http://127.0.0.1:8000';
const chromaHost = new URL(chromaUrl);
const chroma = new ChromaClient({
  host: chromaHost.hostname,
  port: parseInt(chromaHost.port, 10) || 8000,
  ssl: chromaHost.protocol === 'https:',
});

const COLLECTION_NAME = 'gap-clusters';

// We always pass embeddings explicitly, so Chroma never needs to generate
// its own — this stub avoids it trying to load @chroma-core/default-embed.
const noopEmbeddingFunction = {
  generate: async () => {
    throw new Error('Embeddings should be provided manually and never generated by Chroma.');
  },
};

/**
 * Returns (or creates) the `gap-clusters` collection. Pinned to cosine space
 * at creation time so that distance → similarity is `1 - distance`, matching
 * the existing SIMILARITY_THRESHOLD in gap-detect.js (tuned against cosine).
 *
 * @returns {Promise<import('chromadb').Collection>}
 */
async function getCollection() {
  return chroma.getOrCreateCollection({
    name: COLLECTION_NAME,
    embeddingFunction: noopEmbeddingFunction,
    metadata: { 'hnsw:space': 'cosine' },
  });
}

/**
 * Clears the `gap-clusters` collection instead of deleting it. Called at the
 * start of every gap-detect run — the clustering is a full rebuild from
 * query-log.jsonl each time, so the collection is transient storage.
 *
 * We use delete() instead of deleteCollection() to avoid the ChromaNotFoundError
 * that occurs when the collection reference becomes stale during long-running
 * operations with many timeouts.
 *
 * @returns {Promise<import('chromadb').Collection>}
 */
export async function resetClusters() {
  const collection = await getCollection();
  try {
    await collection.delete();
  } catch {
    // Collection is empty or doesn't exist yet — fine.
  }
  return collection;
}

/**
 * ANN nearest-cluster lookup. Returns the closest existing cluster if the
 * collection is non-empty, or `null` if there are no clusters yet.
 *
 * Chroma cosine space returns distance ∈ [0, 2]; we convert to similarity
 * via `1 - distance` so callers can compare directly against their cosine
 * similarity threshold (e.g. SIMILARITY_THRESHOLD = 0.83).
 *
 * @param {import('chromadb').Collection} collection
 * @param {number[]} embedding
 * @returns {Promise<{id: string, similarity: number, metadata: object, centroidEmbedding: number[]}|null>}
 */
export async function findNearestCluster(collection, embedding) {
  // Chroma throws if you query an empty collection — guard with count().
  // Retry a few times to handle transient collection state after recreation.
  let count;
  for (let i = 0; i < 3; i++) {
    try {
      count = await collection.count();
      break;
    } catch (err) {
      if (i === 2) throw err;
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }
  if (count === 0) return null;

  const results = await collection.query({
    queryEmbeddings: [embedding],
    nResults: 1,
    include: ['metadatas', 'embeddings', 'distances'],
  });

  const ids = results.ids?.[0] ?? [];
  if (ids.length === 0) return null;

  const distance = results.distances[0][0];
  const similarity = 1 - distance;
  const metadata = results.metadatas[0][0];
  const centroidEmbedding = results.embeddings[0][0];

  return {
    id: ids[0],
    similarity,
    metadata,
    centroidEmbedding,
  };
}

/**
 * Insert or update a single cluster. The embedding is the running centroid;
 * metadata carries the scalar fields (representative, hitCount, lastSeen,
 * channel) plus the JSON-stringified member list.
 *
 * @param {import('chromadb').Collection} collection
 * @param {string} id
 * @param {number[]} centroid
 * @param {{representative: string, membersJson: string, hitCount: number, lastSeen: string, channel: string}} metadata
 */
export async function upsertCluster(collection, id, centroid, metadata) {
  await collection.upsert({
    ids: [id],
    embeddings: [centroid],
    metadatas: [metadata],
  });
}

/**
 * Returns every cluster currently in the collection. Used by rankClusters()
 * after the clustering pass to score and sort them for the notification loop.
 *
 * @param {import('chromadb').Collection} collection
 * @returns {Promise<{id: string, embedding: number[]|null, metadata: object}[]>}
 */
export async function listClusters(collection) {
  // Retry a few times to handle transient collection state after recreation.
  let count;
  for (let i = 0; i < 3; i++) {
    try {
      count = await collection.count();
      break;
    } catch (err) {
      if (i === 2) throw err;
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }
  if (count === 0) return [];

  const results = await collection.get({
    include: ['metadatas', 'embeddings'],
  });

  const ids = results.ids ?? [];
  const metadatas = results.metadatas ?? [];
  const embeddings = results.embeddings ?? [];

  return ids.map((id, i) => ({
    id,
    embedding: embeddings[i] ?? null,
    metadata: metadatas[i] ?? {},
  }));
}
