import fs from 'fs';
import path from 'path';
import { ChromaClient } from 'chromadb';
import { OpenAI } from 'openai';
import { updateUsageLedger } from './usage-ledger.js';

const openai = new OpenAI({
  apiKey: process.env.GITHUB_TOKEN,
  baseURL: 'https://models.github.ai/inference',
});

const chroma = new ChromaClient();
const COLLECTION_NAME = 'docs';
const EMBEDDING_MODEL = 'openai/text-embedding-3-small';

// We always pass embeddings explicitly, so Chroma never needs to generate
// its own — this stub avoids it trying to load @chroma-core/default-embed.
const noopEmbeddingFunction = {
  generate: async () => {
    throw new Error('Embeddings should be provided manually and never generated by Chroma.');
  },
};

// Phase-2 foundation: append every query + retrieval result to a local
// JSON-lines log. Swap this for a real Postgres insert once you're past
// prototyping — the shape stays the same either way.
const LOG_PATH = path.join(process.cwd(), 'query-log.jsonl');

// Chroma's default space is L2 distance (lower = more similar). It always
// returns your top-`nResults` nearest neighbors as long as the collection
// isn't empty — even if none of them are actually relevant to the question.
// So "did we get docs back" is NOT the same as "did we find an answer".
// This threshold is what actually separates "real hit" from "nearest thing
// we had, which wasn't close." Calibrated against observed scores in
// query-log.jsonl: genuine hits for this corpus cluster around 0.9–1.7,
// while truly off-topic queries (e.g. asking about things not in any doc)
// tend to score even higher. Set conservatively high so we don't refuse
// valid questions; lower it once you have more docs and query data.
const RELEVANCE_THRESHOLD = 1.8;

function logQuery(entry) {
  fs.appendFileSync(LOG_PATH, JSON.stringify(entry) + '\n');
}

/**
 * Embeds a question, retrieves the most relevant chunks from the vector
 * store, and returns both the context text and a confidence signal.
 *
 * @param {string} question
 * @returns {Promise<{context: string, sources: string[], topScore: number|null, hasResults: boolean}>}
 */
export async function retrieveContext(question, { channel, thread_ts } = {}) {
  const embeddingRes = await openai.embeddings.create({
    model: EMBEDDING_MODEL,
    input: question,
  });

  try {
    const collection = await chroma.getOrCreateCollection({
      name: COLLECTION_NAME,
      embeddingFunction: noopEmbeddingFunction,
    });
    const results = await collection.query({
      queryEmbeddings: [embeddingRes.data[0].embedding],
      nResults: 4,
    });

    const docs = results.documents?.[0] ?? [];
    const metas = results.metadatas?.[0] ?? [];
    const distances = results.distances?.[0] ?? [];

    const topScore = distances.length > 0 ? distances[0] : null; // lower = more similar (Chroma L2)

    // docs.length > 0 alone isn't a relevance signal — Chroma returns nearest
    // neighbors regardless of how far away they are. Require the closest one
    // to actually clear the relevance bar.
    const hasResults = docs.length > 0 && topScore !== null && topScore <= RELEVANCE_THRESHOLD;
    const context = docs.join('\n---\n');
    const sources = [...new Set(metas.map((m) => m?.source).filter(Boolean))];

    if (hasResults && sources.length > 0) {
      updateUsageLedger(sources, 'citedCount');
    }

    logQuery({
      question,
      topScore,
      hasResults,
      sources,
      channel,
      thread_ts,
      timestamp: new Date().toISOString(),
    });

    return { context, sources, topScore, hasResults };
  } catch (error) {
    console.error('ChromaDB error during retrieval:', error.message);
    // Return empty results if Chroma fails, allowing the bot to still function
    logQuery({
      question,
      topScore: null,
      hasResults: false,
      sources: [],
      channel,
      thread_ts,
      timestamp: new Date().toISOString(),
      chromaError: error.message,
    });
    return { context: '', sources: [], topScore: null, hasResults: false };
  }
}

/**
 * Records the final generated answer against its logged query so Phase 2
 * (gap detection) has the full question -> answer -> confidence chain.
 * Also used by threadReplyCallback to supply the bot's answer text to
 * judgeFollowUp for accurate correction classification.
 */
export function logAnswer(question, answerText, { channel, thread_ts } = {}) {
  logQuery({
    question,
    answerText,
    channel,
    thread_ts,
    timestamp: new Date().toISOString(),
    type: 'answer',
  });
}

/**
 * Looks up the most recent retrieveContext log entry for a given thread.
 * Returns the entry's question, sources, and bot answer text (if recorded).
 *
 * @param {string} channel
 * @param {string} thread_ts
 * @returns {{ question: string, sources: string[], answerText: string|null } | null}
 */
export function getLastAnswerForThread(channel, thread_ts) {
  if (!fs.existsSync(LOG_PATH)) return null;
  const lines = fs.readFileSync(LOG_PATH, 'utf-8').trim().split('\n').filter(Boolean);

  let retrieveEntry = null;
  let answerEntry = null;

  // Walk backwards — find the most recent retrieve + answer pair for this thread
  for (let i = lines.length - 1; i >= 0; i--) {
    let entry;
    try { entry = JSON.parse(lines[i]); } catch { continue; }
    if (entry.channel !== channel || entry.thread_ts !== thread_ts) continue;

    if (!answerEntry && entry.type === 'answer') {
      answerEntry = entry;
    } else if (!retrieveEntry && entry.type !== 'answer') {
      retrieveEntry = entry;
    }
    if (retrieveEntry && answerEntry) break;
  }

  if (!retrieveEntry) return null;
  return {
    question: retrieveEntry.question,
    sources: retrieveEntry.sources ?? [],
    answerText: answerEntry?.answerText ?? null,
  };
}